# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finish_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_finish_screen(object):
    def setupUi(self, finish_screen):
        finish_screen.setObjectName("finish_screen")
        finish_screen.resize(737, 214)
        self.verticalLayout = QtWidgets.QVBoxLayout(finish_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(finish_screen)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.label = QtWidgets.QLabel(finish_screen)
        self.label.setMinimumSize(QtCore.QSize(100, 60))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(finish_screen)
        QtCore.QMetaObject.connectSlotsByName(finish_screen)

    def retranslateUi(self, finish_screen):
        _translate = QtCore.QCoreApplication.translate
        finish_screen.setWindowTitle(_translate("finish_screen", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("finish_screen", "Ваш ответ"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("finish_screen", "Верный ответ"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("finish_screen", "Задача №1"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("finish_screen", "n1"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("finish_screen", "n2"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("finish_screen", "Всего правильных ответов:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Test1 = Ui_finish_screen()
    Test1.show()
    sys.exit(app.exec_())