# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testv1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView



class Ui_Test1(object):
    def setupUi(self, Test1):
        Test1.setObjectName("Test1")
        Test1.resize(921, 621)
        self.verticalLayout = QtWidgets.QVBoxLayout(Test1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.testwidget = QtWidgets.QStackedWidget(Test1)
        self.testwidget.setObjectName("testwidget")
        self.quest1 = QtWidgets.QWidget()
        self.quest1.setObjectName("quest1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.quest1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        

        self.webEngineView = QWebEngineView(self.quest1)
        self.webEngineView.setObjectName("webEngineView")
        self.verticalLayout_2.addWidget(self.webEngineView)
        self.answeredit = QtWidgets.QLineEdit(self.quest1)
        self.answeredit.setObjectName("answeredit")
        self.verticalLayout_2.addWidget(self.answeredit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(10, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.prev_qst_btn = QtWidgets.QPushButton(self.quest1)
        self.prev_qst_btn.setMaximumSize(QtCore.QSize(130, 16777215))
        self.prev_qst_btn.setObjectName("prev_qst_btn")
        self.horizontalLayout_2.addWidget(self.prev_qst_btn)
        self.next_qst_btn = QtWidgets.QPushButton(self.quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_qst_btn.sizePolicy().hasHeightForWidth())
        self.next_qst_btn.setSizePolicy(sizePolicy)
        self.next_qst_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.next_qst_btn.setMaximumSize(QtCore.QSize(130, 16777215))
        self.next_qst_btn.setSizeIncrement(QtCore.QSize(0, 0))
        self.next_qst_btn.setIconSize(QtCore.QSize(16, 5))
        self.next_qst_btn.setObjectName("next_qst_btn")
        self.horizontalLayout_2.addWidget(self.next_qst_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.testwidget.addWidget(self.quest1)
        self.verticalLayout.addWidget(self.testwidget)

        self.retranslateUi(Test1)
        self.testwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Test1)

    def retranslateUi(self, Test1):
        _translate = QtCore.QCoreApplication.translate
        Test1.setWindowTitle(_translate("Test1", "Dialog"))
        
        self.prev_qst_btn.setText(_translate("Test1", "Предыдущий вопрс"))
        self.next_qst_btn.setText(_translate("Test1", "Следующий вопрос"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Test1 = QtWidgets.QWidget()
    ui = Ui_Test1()
    ui.setupUi(Test1)
    Test1.show()
    sys.exit(app.exec_())